events {
        worker_connections  1024;
    }

http {
    # Load balancer configuration, default RoundRobin Style
    upstream backend { #Can rename backend to anything
        #ip_hash; <-- used for sticky sessions (user gets directed to same server upon page refresh)
        server flask:5000;
        #server localhost:8001;
    }

    server {
        server_tokens off; #Prevent HTTP header NGINX version exposure
        listen 80; # ipv4, ignoring ipv6 for the time being
        server_name localhost; #REPLACE LATER maybe

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            # proxy_set_header X-Forwarded-Host $host; <-- Only used when NGINX is the webserver
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Upgrade $http_upgrade; # Websocket support
            proxy_set_header Connection "upgrade"; # Updates connection based on the header above
        }
    }
}
